events { worker_connections 2048; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 8888;

        location / {
            root /opt/app/frontend/dist;
            try_files $uri $uri/ /index.html;
        }

        location /realtime {
            proxy_pass http://127.0.0.1:8080/realtime;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }
    }
}
